Adding support for long-format hash
josa42/atom-blame pull request #38
Opened 2017-05-02 21:04 UTC by Xapphire13

Some repository browsers require the full long-format hash to work (VSO for example). Adding support for `{lhash}` placeholder

2017-05-10 21:56 UTC, Xapphire13 commented
Ping =]

2017-05-11 07:19 UTC, josa42 requested changes

2017-05-11 07:19 UTC, josa42 commented on README.md
> +`{lhash}` will be replaced with the long-format hash of selected commit.
I find `{hash}` and `{lhash}` hard to differentiate. Could we change `{lhash}` to `{long-hash}`?

2017-05-12 00:49 UTC, Xapphire13 commented on README.md
> +`{lhash}` will be replaced with the long-format hash of selected commit.
Good idea =]

2017-05-23 05:45 UTC, merged

2017-05-23 06:20 UTC, Xapphire13 commented
Thanks @josa42!

2017-05-23 07:06 UTC, josa42 commented
@Xapphire13 Thank you for the contribution. And sorry for being so lazy and letting this sit here for so long 😆